baseURL = 'https://example.org/'
languageCode = 'es-es'
title = 'Los Olvidados de Canción de Hielo y Fuego'
theme = 'm10c'

[params]
	avatar = 'images/rheagar_lyanna.jpg'
	description = 'Personajes y tramas olvidados y cambiados en la adaptación cinematográfica'

[menu]
	[[menu.main]]
	name = "Inicio"
	url = "/"
	weight = 1

	[[menu.main]]
	name = "Personajes"
	url = "/personajes/"
	weight = 2

	[[menu.main]]
	name = "Tramas"
	url = "/tramas/"
	weight = 3

	[[menu.main]]
	name = "Teorías"
	url = "/teorias/"
	weight = 4
